name: one-engine-ci
on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Build
        env:
          BUILD_TOKEN: ${{ github.sha }}
          GIT_REF: ${{ github.ref }}
        run: cargo build --release
      - name: Smoke test
        run: ./target/release/one-engine --help || true
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: one-engine-linux-amd64-v2
          path: target/release/one-engine
