name: meta2-guard
on:
  pull_request:
    paths:
      - 'policies/**'
      - 'src/engine/kernel.rs'

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check META2 compliance
        run: |
          # Fail if L2 params changed without META2_PRIMER.md
          if git diff --name-only origin/main | grep -E "(kernel\.rs|POLICY\.)" && ! git diff --name-only origin/main | grep "META2_PRIMER.md"; then
            echo "❌ L2 parameter changes require META2_PRIMER.md"
            exit 1
          fi
          
          # Check shadow rollout percentage
          if [ -f "META2_PRIMER.md" ]; then
            if ! grep -q "shadow.*20%" META2_PRIMER.md; then
              echo "❌ META2 changes require shadow rollout ≥ 20%"
              exit 1
            fi
          fi
          
          echo "✅ META2 compliance verified"
