name: ops-ledger
on: [push, pull_request]
jobs:
  ops:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python3 -V || sudo apt-get update && sudo apt-get install -y python3 jq
      - run: mkdir -p _trace _episodes _notebook
      - run: echo '{"ts":"now","goal":"dryrun","bits":{"a":1,"e":0,"d":0,"t":0.9}}' > _trace/dryrun.json
      - run: python3 tools/bundles.py
      - run: python3 tools/check_policy.py || (echo "::notice::policy check failed (no data)"; exit 0)
