name: PR Title Check

on:
  pull_request_target:
    types: [opened, edited, synchronize]

jobs:
  lint:
    permissions:
      pull-requests: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |-
            feat
            fix
            docs
            chore
            refactor
            perf
            test
            ci
            build
            revert
          requireScope: false

