openapi: 3.1.0
info: {title: One Engine, version: 0.1.0}
paths:
  /healthz: {get: {operationId: health, responses: {"200": {description: OK}}}}
  /plan:
    post:
      operationId: plan
      requestBody: {required: true, content: {application/json: {schema: {type: object}}}}
      responses: {"200": {description: Plan}}
  /run:
    post:
      operationId: run
      requestBody: {required: true, content: {application/json: {schema: {type: object}}}}
      responses: {"200": {description: Run}}
  /episodes:
    get: {operationId: episodes, responses: {"200": {description: Episodes}}}
  /trace/{id}:
    get:
      operationId: trace
      parameters: [{name: id, in: path, required: true, schema: {type: string}}]
      responses: {"200": {description: Trace}}
